### ISSUE TITLE
README.md updated after multiple people had already pushed additions

### ISSUE THREAD

**Issue by panos1b** [ibalampanis/ai-ethics#1]
The `README.md` was updated in commit e7ebc621f29cd91a5aa39f0a8bb30a03a747a8dd even though multiple people had already committed in accordance to the previous `README.md`. 
Requesting the rollback of commit e7ebc621f29cd91a5aa39f0a8bb30a03a747a8dd in order to not hinder progress on the repo.

**Comment by karyotakisg** [comment]
Seems reasonable.

**Comment by ibalampanis** [comment]
Don't worry. It was a typo from my side. It will in no way affect your work. Keep pushing! Thanks.

**Comment by panos1b** [comment]
Good to know!
